import cadquery as cq 

pedal = (cq.Workplane('XY')
    .rect(20, 10)
    .extrude(30)
    .center(0, -5)
    .circle(10)
    .extrude(30)
    .workplane()
    .polygon(6, 12)
    .cutThruAll()
    .faces(">Y")
    .workplane()
    .rect(20, 10)
    .cutThruAll()
    .faces(">Y")
    .workplane()
    .rect(20, 30)
    .extrude(20)
    .faces(">Y")
    .rect(20, 20)
    .extrude(10)
    .faces(">Y")
    .workplane()
    .rect(3, 10)
    .cutThruAll()
    .faces(">Y")
    .workplane()
    .rect(20, 20)
    .extrude(100)
    .faces(">Y")
    .rect(20, 50)
    .extrude(50)
    )

base = (cq.Workplane('ZY')
    .rect(50, 50)
    .extrude(5)
    .faces(">X")
    .workplane()
    .pushPoints([(-15, -20.5), (-15, 20.5)])
    .rect(20, 9)
    .extrude(20)
    .faces(">Z")
    .workplane(origin=(10,-15,0))
    .hole(12)
    )

shaft = (cq.Workplane('ZY')
    .polygon(6, 10)
    .extrude(65)
    )

plate = (cq.Workplane('XY')
    .rect(50, 100)
    .rect(150, 140)
    .extrude(5)
    )

cq.exporters.export(pedal, "pedal.stl")
cq.exporters.export(base, "pedal-base.stl")
cq.exporters.export(shaft, "pedal-shaft.stl")
cq.exporters.export(plate, "pedal-plate.stl")
